### PR TITLE
Fix KPH and add millimeters_per_second which is in ExoSense

### PR DESCRIPTION
**Pull request by alecjohanson**

### CODE REVIEW

**Comment by alecjohanson** [comment]
https://exosite.atlassian.net/browse/DOCS-79
https://exosite.atlassian.net/browse/DOCS-78

**Comment by alecjohanson** [comment]
@maanenson

**Review by maanenson — APPROVED** [review]
looks good

**Comment by alecjohanson** [comment]
@maanenson I don't have permission to merge.

**Pull request merged**
